# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chromatic docs
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: '/docs' # the subpath of your site, e.g. /blog
url: 'https://www.chromatic.com' # the base hostname & protocol for your site

# Build settings
markdown: CommonMarkGhPages
commonmark:
  options: ['SMART', 'FOOTNOTES']
  # https://github.com/gjtorikian/commonmarker#extensions
  extensions: ['strikethrough', 'autolink', 'table', 'tagfilter']
# kramdown:
#   syntax_highlighter: rouge
#   parse_block_html: true

# Sites
url_blog: https://blog.hichroma.com

# Social
twitter_username: chromaui

exclude:
  - node_modules
  - _posts
  - gruntfile.js
  - npm-debug.log
