name: Update docs ✍️
description: >-
  Find a mistake in our documentation, or have a suggestion to improve them? Let us know here.
title: "[Documentation]: "
labels:
  - needs triage
  - documentation
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: A clear and concise description of what is wrong in the documentation or what you would like to improve.
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL of the page with the issue
      description: Please include URL to the pages you're referring to.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
