%%{
  init: { 'theme': 'natural', 'themeVariables': { 'tagLabelFontSize': '12px' } }
}%%
gitGraph
  commit id: "A"
  branch feature
  commit id: "P" tag: "an. A"
  checkout main
  commit id: "B" tag: "an. A"
  commit id: "C" tag: "an. B"
  checkout feature
  branch ephemeral
  commit id: "P'" tag: "ephemeral from D" type: HIGHLIGHT
  checkout main
  merge ephemeral id: "D" tag: "an. C"
