%%{
  init: {
    'gitGraph': { 'parallelCommits': true, 'mainBranchName': 'main' }
  }
}%%
gitGraph TB:
  checkout main
  commit id: "X" type: HIGHLIGHT
  branch feature-branch
  commit id: "A" tag: "unwanted changes"
  commit id: "B"
  commit id: "C" type: HIGHLIGHT
