name: 'Broken link checker'
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  check-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        name: Install pnpm
        with:
          cache: true
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Check links
        id: check-links
        run: pnpm run check-links
      - name: Send failure status to slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
        with:
          payload: |
            {
              "status": "🔴 Found broken links",
              "report": "https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
